## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [6]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [8]:
df_mat['Matemática (%)'] = (df_mat['Qt_acertos'] / 24) * 100
df_por['Português (%)'] = (df_por['Qt_acertos'] / 18) * 100
df_geo['Geografia (%)'] = (df_geo['Qt_acertos'] / 8) * 100
df_ing['Inglês (%)'] = (df_ing['Qt_acertos'] / 8) * 100
df_his['História (%)'] = (df_his['Qt_acertos'] / 8) * 100
df_fis['Física (%)'] = (df_fis['Qt_acertos'] / 12) * 100
df_qui['Química (%)'] = (df_qui['Qt_acertos'] / 12) * 100

df = pd.concat([df_mat, df_por, df_geo, df_ing, df_his, df_fis, df_qui], axis=1)
df

,Qt_acertos,Matemática (%),Qt_acertos,Português (%),Qt_acertos,Geografia (%),Qt_acertos,Inglês (%),Qt_acertos,História (%),Qt_acertos,Física (%),Qt_acertos,Química (%)
0,6,25.000000,7,38.888889,7,87.5,3,37.5,1,12.5,8,66.666667,3,25.000000
1,19,79.166667,10,55.555556,0,0.0,0,0.0,0,0.0,11,91.666667,8,66.666667
2,14,58.333333,16,88.888889,0,0.0,5,62.5,7,87.5,4,33.333333,4,33.333333
3,10,41.666667,7,38.888889,3,37.5,4,50.0,0,0.0,0,0.000000,8,66.666667
4,7,29.166667,2,11.111111,2,25.0,7,87.5,0,0.0,9,75.000000,3,25.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,6,25.000000,4,22.222222,7,87.5,1,12.5,4,50.0,9,75.000000,3,25.000000
96,8,33.333333,1,5.555556,4,50.0,6,75.0,1,12.5,4,33.333333,3,25.000000
97,23,95.833333,5,27.777778,0,0.0,2,25.0,4,50.0,1,8.333333,5,41.666667
98,0,0.000000,10,55.555556,3,37.5,1,12.5,5,62.5,10,83.333333,11,91.666667
99,11,45.833333,15,83.333333,0,0.0,1,12.5,6,75.0,7,58.333333,2,16.666667

In [10]:
df['Total_acertos'] = df_mat['Qt_acertos'] + df_por['Qt_acertos'] + df_geo['Qt_acertos'] + df_ing['Qt_acertos'] + df_his['Qt_acertos'] + df_fis['Qt_acertos'] + df_qui['Qt_acertos']
df

,Qt_acertos,Matemática (%),Qt_acertos,Português (%),Qt_acertos,Geografia (%),Qt_acertos,Inglês (%),Qt_acertos,História (%),Qt_acertos,Física (%),Qt_acertos,Química (%),Total_acertos
0,6,25.000000,7,38.888889,7,87.5,3,37.5,1,12.5,8,66.666667,3,25.000000,35
1,19,79.166667,10,55.555556,0,0.0,0,0.0,0,0.0,11,91.666667,8,66.666667,48
2,14,58.333333,16,88.888889,0,0.0,5,62.5,7,87.5,4,33.333333,4,33.333333,50
3,10,41.666667,7,38.888889,3,37.5,4,50.0,0,0.0,0,0.000000,8,66.666667,32
4,7,29.166667,2,11.111111,2,25.0,7,87.5,0,0.0,9,75.000000,3,25.000000,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,6,25.000000,4,22.222222,7,87.5,1,12.5,4,50.0,9,75.000000,3,25.000000,34
96,8,33.333333,1,5.555556,4,50.0,6,75.0,1,12.5,4,33.333333,3,25.000000,27
97,23,95.833333,5,27.777778,0,0.0,2,25.0,4,50.0,1,8.333333,5,41.666667,40
98,0,0.000000,10,55.555556,3,37.5,1,12.5,5,62.5,10,83.333333,11,91.666667,40
99,11,45.833333,15,83.333333,0,0.0,1,12.5,6,75.0,7,58.333333,2,16.666667,42

In [12]:
df['Percentual_geral'] = df['Total_acertos']/90 * 100
df

,Qt_acertos,Matemática (%),Qt_acertos,Português (%),Qt_acertos,Geografia (%),Qt_acertos,Inglês (%),Qt_acertos,História (%),Qt_acertos,Física (%),Qt_acertos,Química (%),Total_acertos,Percentual_geral
0,6,25.000000,7,38.888889,7,87.5,3,37.5,1,12.5,8,66.666667,3,25.000000,35,38.888889
1,19,79.166667,10,55.555556,0,0.0,0,0.0,0,0.0,11,91.666667,8,66.666667,48,53.333333
2,14,58.333333,16,88.888889,0,0.0,5,62.5,7,87.5,4,33.333333,4,33.333333,50,55.555556
3,10,41.666667,7,38.888889,3,37.5,4,50.0,0,0.0,0,0.000000,8,66.666667,32,35.555556
4,7,29.166667,2,11.111111,2,25.0,7,87.5,0,0.0,9,75.000000,3,25.000000,30,33.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,6,25.000000,4,22.222222,7,87.5,1,12.5,4,50.0,9,75.000000,3,25.000000,34,37.777778
96,8,33.333333,1,5.555556,4,50.0,6,75.0,1,12.5,4,33.333333,3,25.000000,27,30.000000
97,23,95.833333,5,27.777778,0,0.0,2,25.0,4,50.0,1,8.333333,5,41.666667,40,44.444444
98,0,0.000000,10,55.555556,3,37.5,1,12.5,5,62.5,10,83.333333,11,91.666667,40,44.444444
99,11,45.833333,15,83.333333,0,0.0,1,12.5,6,75.0,7,58.333333,2,16.666667,42,46.666667

In [16]:
df_acima_45 = df[df['Percentual_geral'] > 45].shape[0]
df_acima_45

47

In [18]:
df_acima_45_lista = df[df['Percentual_geral'] > 45]
df_acima_45_lista

,Qt_acertos,Matemática (%),Qt_acertos,Português (%),Qt_acertos,Geografia (%),Qt_acertos,Inglês (%),Qt_acertos,História (%),Qt_acertos,Física (%),Qt_acertos,Química (%),Total_acertos,Percentual_geral
1,19,79.166667,10,55.555556,0,0.0,0,0.0,0,0.0,11,91.666667,8,66.666667,48,53.333333
2,14,58.333333,16,88.888889,0,0.0,5,62.5,7,87.5,4,33.333333,4,33.333333,50,55.555556
5,20,83.333333,2,11.111111,5,62.5,3,37.5,2,25.0,9,75.000000,9,75.000000,50,55.555556
7,18,75.000000,4,22.222222,4,50.0,7,87.5,7,87.5,1,8.333333,8,66.666667,49,54.444444
8,22,91.666667,9,50.000000,2,25.0,7,87.5,6,75.0,5,41.666667,7,58.333333,58,64.444444
11,23,95.833333,6,33.333333,2,25.0,0,0.0,6,75.0,4,33.333333,2,16.666667,43,47.777778
12,20,83.333333,8,44.444444,3,37.5,7,87.5,1,12.5,0,0.000000,3,25.000000,42,46.666667
17,21,87.500000,15,83.333333,2,25.0,2,25.0,4,50.0,2,16.666667,6,50.000000,52,57.777778
18,20,83.333333,4,22.222222,3,37.5,5,62.5,3,37.5,11,91.666667,4,33.333333,50,55.555556
20,23,95.833333,11,61.111111,6,75.0,5,62.5,6,75.0,2,16.666667,0,0.000000,53,58.888889
24,20,83.333333,2,11.111111,7,87.5,5,62.5,3,37.5,11,91.666667,2,16.666667,50,55.555556
27,21,87.500000,13,72.222222,1,12.5,5,62.5,7,87.5,3,25.000000,0,0.000000,50,55.555556
29,16,66.666667,0,0.000000,0,0.0,2,25.0,7,87.5,11,91.666667,8,66.666667,44,48.888889
31,15,62.500000,13,72.222222,3,37.5,1,12.5,3,37.5,9,75.000000,10,83.333333,54,60.000000
34,18,75.000000,14,77.777778,1,12.5,0,0.0,6,75.0,3,25.000000,3,25.000000,45,50.000000
35,11,45.833333,14,77.777778,6,75.0,3,37.5,3,37.5,0,0.000000,11,91.666667,48,53.333333
36,22,91.666667,9,50.000000,6,75.0,6,75.0,1,12.5,4,33.333333,8,66.666667,56,62.222222
37,19,79.166667,12,66.666667,5,62.5,7,87.5,1,12.5,6,50.000000,2,16.666667,52,57.777778
39,4,16.666667,16,88.888889,2,25.0,4,50.0,6,75.0,9,75.000000,8,66.666667,49,54.444444
40,18,75.000000,3,16.666667,6,75.0,3,37.5,6,75.0,5,41.666667,6,50.000000,47,52.222222
42,20,83.333333,6,33.333333,7,87.5,7,87.5,2,25.0,3,25.000000,3,25.000000,48,53.333333
44,6,25.000000,14,77.777778,7,87.5,3,37.5,1,12.5,3,25.000000,9,75.000000,43,47.777778
45,17,70.833333,10,55.555556,0,0.0,2,25.0,6,75.0,9,75.000000,4,33.333333,48,53.333333
48,17,70.833333,6,33.333333,0,0.0,7,87.5,5,62.5,9,75.000000,11,91.666667,55,61.111111
50,20,83.333333,9,50.000000,0,0.0,3,37.5,1,12.5,7,58.333333,3,25.000000,43,47.777778
51,1,4.166667,12,66.666667,7,87.5,3,37.5,5,62.5,4,33.333333,10,83.333333,42,46.666667
52,19,79.166667,5,27.777778,5,62.5,5,62.5,0,0.0,3,25.000000,4,33.333333,41,45.555556
53,14,58.333333,11,61.111111,3,37.5,4,50.0,3,37.5,7,58.333333,3,25.000000,45,50.000000
55,11,45.833333,10,55.555556,4,50.0,4,50.0,5,62.5,1,8.333333,6,50.000000,41,45.555556
60,16,66.666667,8,44.444444,0,0.0,4,50.0,4,50.0,7,58.333333,9,75.000000,48,53.333333
62,17,70.833333,6,33.333333,2,25.0,4,50.0,7,87.5,1,8.333333,9,75.000000,46,51.111111
67,21,87.500000,0,0.000000,7,87.5,2,25.0,4,50.0,2,16.666667,10,83.333333,46,51.111111
68,9,37.500000,9,50.000000,5,62.5,3,37.5,6,75.0,10,83.333333,1,8.333333,43,47.777778
70,21,87.500000,14,77.777778,0,0.0,3,37.5,5,62.5,11,91.666667,8,66.666667,62,68.888889
71,17,70.833333,8,44.444444,7,87.5,6,75.0,4,50.0,2,16.666667,9,75.000000,53,58.888889
72,11,45.833333,16,88.888889,3,37.5,4,50.0,7,87.5,0,0.000000,9,75.000000,50,55.555556
75,3,12.500000,6,33.333333,7,87.5,6,75.0,6,75.0,9,75.000000,5,41.666667,42,46.666667
77,15,62.500000,2,11.111111,5,62.5,7,87.5,6,75.0,11,91.666667,7,58.333333,53,58.888889
78,14,58.333333,16,88.888889,7,87.5,2,25.0,7,87.5,11,91.666667,9,75.000000,66,73.333333
80,13,54.166667,16,88.888889,5,62.5,1,12.5,7,87.5,2,16.666667,1,8.333333,45,50.000000
81,22,91.666667,16,88.888889,2,25.0,0,0.0,4,50.0,1,8.333333,10,83.333333,55,61.111111
82,7,29.166667,16,88.888889,7,87.5,1,12.5,1,12.5,2,16.666667,9,75.000000,43,47.777778
83,20,83.333333,1,5.555556,5,62.5,6,75.0,3,37.5,6,50.000000,1,8.333333,42,46.666667
88,20,83.333333,1,5.555556,1,12.5,5,62.5,7,87.5,9,75.000000,7,58.333333,50,55.555556
89,23,95.833333,11,61.111111,7,87.5,7,87.5,6,75.0,9,75.000000,0,0.000000,63,70.000000
93,12,50.000000,16,88.888889,5,62.5,5,62.5,6,75.0,6,50.000000,6,50.000000,56,62.222222
99,11,45.833333,15,83.333333,0,0.0,1,12.5,6,75.0,7,58.333333,2,16.666667,42,46.666667

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [20]:
desqualificados = df[(df['Matemática (%)'] == 0) | (df['Física (%)'] == 0) | (df['Química (%)'] == 0)]
desqualificados

,Qt_acertos,Matemática (%),Qt_acertos,Português (%),Qt_acertos,Geografia (%),Qt_acertos,Inglês (%),Qt_acertos,História (%),Qt_acertos,Física (%),Qt_acertos,Química (%),Total_acertos,Percentual_geral
3,10,41.666667,7,38.888889,3,37.5,4,50.0,0,0.0,0,0.000000,8,66.666667,32,35.555556
6,6,25.000000,0,0.000000,7,87.5,7,87.5,5,62.5,0,0.000000,4,33.333333,29,32.222222
10,10,41.666667,8,44.444444,3,37.5,2,25.0,1,12.5,7,58.333333,0,0.000000,31,34.444444
12,20,83.333333,8,44.444444,3,37.5,7,87.5,1,12.5,0,0.000000,3,25.000000,42,46.666667
14,7,29.166667,11,61.111111,1,12.5,7,87.5,1,12.5,4,33.333333,0,0.000000,31,34.444444
20,23,95.833333,11,61.111111,6,75.0,5,62.5,6,75.0,2,16.666667,0,0.000000,53,58.888889
25,0,0.000000,4,22.222222,7,87.5,4,50.0,0,0.0,4,33.333333,8,66.666667,27,30.000000
26,11,45.833333,14,77.777778,6,75.0,2,25.0,7,87.5,0,0.000000,0,0.000000,40,44.444444
27,21,87.500000,13,72.222222,1,12.5,5,62.5,7,87.5,3,25.000000,0,0.000000,50,55.555556
33,14,58.333333,8,44.444444,0,0.0,5,62.5,6,75.0,6,50.000000,0,0.000000,39,43.333333
35,11,45.833333,14,77.777778,6,75.0,3,37.5,3,37.5,0,0.000000,11,91.666667,48,53.333333
49,8,33.333333,1,5.555556,1,12.5,0,0.0,1,12.5,0,0.000000,8,66.666667,19,21.111111
56,7,29.166667,6,33.333333,7,87.5,5,62.5,6,75.0,0,0.000000,8,66.666667,39,43.333333
65,1,4.166667,8,44.444444,2,25.0,4,50.0,3,37.5,0,0.000000,6,50.000000,24,26.666667
66,5,20.833333,4,22.222222,3,37.5,6,75.0,3,37.5,0,0.000000,10,83.333333,31,34.444444
72,11,45.833333,16,88.888889,3,37.5,4,50.0,7,87.5,0,0.000000,9,75.000000,50,55.555556
73,1,4.166667,16,88.888889,2,25.0,4,50.0,3,37.5,0,0.000000,11,91.666667,37,41.111111
74,9,37.500000,11,61.111111,0,0.0,7,87.5,5,62.5,7,58.333333,0,0.000000,39,43.333333
84,15,62.500000,1,5.555556,0,0.0,5,62.5,1,12.5,0,0.000000,4,33.333333,26,28.888889
89,23,95.833333,11,61.111111,7,87.5,7,87.5,6,75.0,9,75.000000,0,0.000000,63,70.000000
92,14,58.333333,10,55.555556,1,12.5,6,75.0,1,12.5,8,66.666667,0,0.000000,40,44.444444
94,0,0.000000,5,27.777778,2,25.0,6,75.0,1,12.5,3,25.000000,8,66.666667,25,27.777778
98,0,0.000000,10,55.555556,3,37.5,1,12.5,5,62.5,10,83.333333,11,91.666667,40,44.444444

In [22]:
desqualificados.shape[0]

23

In [24]:
media_his_geo_desqualificados = desqualificados[['História (%)', 'Geografia (%)']].mean()
media_his_geo_desqualificados

História (%)     42.934783
Geografia (%)    40.217391
dtype: float64

In [38]:
df_acima_45_lista = df[df['Percentual_geral'] > 45]

df_qualificados = df_acima_45_lista[(df_acima_45_lista['Matemática (%)'] > 0) & (df_acima_45_lista['Física (%)'] > 0) & (df_acima_45_lista['Química (%)'] > 0)]
df_qualificados

,Qt_acertos,Matemática (%),Qt_acertos,Português (%),Qt_acertos,Geografia (%),Qt_acertos,Inglês (%),Qt_acertos,História (%),Qt_acertos,Física (%),Qt_acertos,Química (%),Total_acertos,Percentual_geral
1,19,79.166667,10,55.555556,0,0.0,0,0.0,0,0.0,11,91.666667,8,66.666667,48,53.333333
2,14,58.333333,16,88.888889,0,0.0,5,62.5,7,87.5,4,33.333333,4,33.333333,50,55.555556
5,20,83.333333,2,11.111111,5,62.5,3,37.5,2,25.0,9,75.000000,9,75.000000,50,55.555556
7,18,75.000000,4,22.222222,4,50.0,7,87.5,7,87.5,1,8.333333,8,66.666667,49,54.444444
8,22,91.666667,9,50.000000,2,25.0,7,87.5,6,75.0,5,41.666667,7,58.333333,58,64.444444
11,23,95.833333,6,33.333333,2,25.0,0,0.0,6,75.0,4,33.333333,2,16.666667,43,47.777778
17,21,87.500000,15,83.333333,2,25.0,2,25.0,4,50.0,2,16.666667,6,50.000000,52,57.777778
18,20,83.333333,4,22.222222,3,37.5,5,62.5,3,37.5,11,91.666667,4,33.333333,50,55.555556
24,20,83.333333,2,11.111111,7,87.5,5,62.5,3,37.5,11,91.666667,2,16.666667,50,55.555556
29,16,66.666667,0,0.000000,0,0.0,2,25.0,7,87.5,11,91.666667,8,66.666667,44,48.888889
31,15,62.500000,13,72.222222,3,37.5,1,12.5,3,37.5,9,75.000000,10,83.333333,54,60.000000
34,18,75.000000,14,77.777778,1,12.5,0,0.0,6,75.0,3,25.000000,3,25.000000,45,50.000000
36,22,91.666667,9,50.000000,6,75.0,6,75.0,1,12.5,4,33.333333,8,66.666667,56,62.222222
37,19,79.166667,12,66.666667,5,62.5,7,87.5,1,12.5,6,50.000000,2,16.666667,52,57.777778
39,4,16.666667,16,88.888889,2,25.0,4,50.0,6,75.0,9,75.000000,8,66.666667,49,54.444444
40,18,75.000000,3,16.666667,6,75.0,3,37.5,6,75.0,5,41.666667,6,50.000000,47,52.222222
42,20,83.333333,6,33.333333,7,87.5,7,87.5,2,25.0,3,25.000000,3,25.000000,48,53.333333
44,6,25.000000,14,77.777778,7,87.5,3,37.5,1,12.5,3,25.000000,9,75.000000,43,47.777778
45,17,70.833333,10,55.555556,0,0.0,2,25.0,6,75.0,9,75.000000,4,33.333333,48,53.333333
48,17,70.833333,6,33.333333,0,0.0,7,87.5,5,62.5,9,75.000000,11,91.666667,55,61.111111
50,20,83.333333,9,50.000000,0,0.0,3,37.5,1,12.5,7,58.333333,3,25.000000,43,47.777778
51,1,4.166667,12,66.666667,7,87.5,3,37.5,5,62.5,4,33.333333,10,83.333333,42,46.666667
52,19,79.166667,5,27.777778,5,62.5,5,62.5,0,0.0,3,25.000000,4,33.333333,41,45.555556
53,14,58.333333,11,61.111111,3,37.5,4,50.0,3,37.5,7,58.333333,3,25.000000,45,50.000000
55,11,45.833333,10,55.555556,4,50.0,4,50.0,5,62.5,1,8.333333,6,50.000000,41,45.555556
60,16,66.666667,8,44.444444,0,0.0,4,50.0,4,50.0,7,58.333333,9,75.000000,48,53.333333
62,17,70.833333,6,33.333333,2,25.0,4,50.0,7,87.5,1,8.333333,9,75.000000,46,51.111111
67,21,87.500000,0,0.000000,7,87.5,2,25.0,4,50.0,2,16.666667,10,83.333333,46,51.111111
68,9,37.500000,9,50.000000,5,62.5,3,37.5,6,75.0,10,83.333333,1,8.333333,43,47.777778
70,21,87.500000,14,77.777778,0,0.0,3,37.5,5,62.5,11,91.666667,8,66.666667,62,68.888889
71,17,70.833333,8,44.444444,7,87.5,6,75.0,4,50.0,2,16.666667,9,75.000000,53,58.888889
75,3,12.500000,6,33.333333,7,87.5,6,75.0,6,75.0,9,75.000000,5,41.666667,42,46.666667
77,15,62.500000,2,11.111111,5,62.5,7,87.5,6,75.0,11,91.666667,7,58.333333,53,58.888889
78,14,58.333333,16,88.888889,7,87.5,2,25.0,7,87.5,11,91.666667,9,75.000000,66,73.333333
80,13,54.166667,16,88.888889,5,62.5,1,12.5,7,87.5,2,16.666667,1,8.333333,45,50.000000
81,22,91.666667,16,88.888889,2,25.0,0,0.0,4,50.0,1,8.333333,10,83.333333,55,61.111111
82,7,29.166667,16,88.888889,7,87.5,1,12.5,1,12.5,2,16.666667,9,75.000000,43,47.777778
83,20,83.333333,1,5.555556,5,62.5,6,75.0,3,37.5,6,50.000000,1,8.333333,42,46.666667
88,20,83.333333,1,5.555556,1,12.5,5,62.5,7,87.5,9,75.000000,7,58.333333,50,55.555556
93,12,50.000000,16,88.888889,5,62.5,5,62.5,6,75.0,6,50.000000,6,50.000000,56,62.222222
99,11,45.833333,15,83.333333,0,0.0,1,12.5,6,75.0,7,58.333333,2,16.666667,42,46.666667

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [ ]:
# Adicionar o arquivo de leitura

In [26]:
arquivo = 'registros de vacinacao covid ACRE.csv'

In [56]:
df = pd.read_csv(arquivo, sep=';')
df.head()

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
0,b19cd280-474c-4c22-a35d-8c06bc04a4e0-i0b0,2e091c9a37d3f50d1d705fc80c6448c6fc69b44da9e936...,69,1951-12-28,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,210052A,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-23,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-25T03:27:19.000Z,NaN
1,a1acc0b6-1cf6-4c4b-adcb-06b473a0faaf-i0b0,f4e17a9e5354cb45e223d85eda02fb2f76048c801675f5...,81,1939-11-22,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,210110,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-29,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-30T16:03:14.000Z,NaN
2,af279a98-ba1f-47ea-8214-314a98040b0d-i0b0,6734b26bccf826130ebffa66575977bbe71477b12bcf42...,69,1951-08-14,M,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,210135,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-16,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-16T15:54:39.000Z,NaN
3,4879308e-5050-46bb-b8e2-11fa5646a05c-i0b0,84a341fd350c1ba7117fccbb4d2df417bc0fac0fffac37...,51,1969-12-15,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,202010040,FUNDACAO BUTANTAN,Organization/61189445000156,2021-02-19,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-10T14:40:54.000Z,NaN
4,000e911b-e3a4-4114-a735-d1f2e6e3797f-i0b0,c59571e19f368d4b0cf08cd3bcabb32e5cd8baad5340f6...,65,1955-11-21,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-03-29,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-03T19:44:28.000Z,NaN

In [ ]:
# 1) Quantas vacinas estão registradas nessa base?

In [42]:
df["vacina_nome"].nunique()

5

In [ ]:
# 2) Quantos pacientes foram vacinados? (considere um paciente para cada valor único de paciente_id)

In [44]:
df["paciente_id"].nunique()

120517

In [ ]:
# 3) Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método .unique().

In [60]:
df["fl_primeira_dose"] = 0

In [72]:
df["vacina_descricao_dose"].unique()

array(['\xa0\xa0\xa0\xa01ª\xa0Dose', '\xa0\xa0\xa0\xa02ª\xa0Dose',
       '\xa0\xa0\xa0\xa0Dose\xa0'], dtype=object)

In [80]:
df.loc[df["vacina_descricao_dose"] == '\xa0\xa0\xa0\xa01ª\xa0Dose', "fl_primeira_dose"] = 1

In [82]:
df[["vacina_descricao_dose","fl_primeira_dose"]]

       vacina_descricao_dose  fl_primeira_dose
0                    1ª Dose                 1
1                    2ª Dose                 0
2                    1ª Dose                 1
3                    2ª Dose                 0
4                    1ª Dose                 1
...                      ...               ...
169066               1ª Dose                 1
169067               1ª Dose                 1
169068               1ª Dose                 1
169069               1ª Dose                 1
169070               1ª Dose                 1

[169071 rows x 2 columns]

In [ ]:
# 4) Quantos pacientes com menos de 18 anos foram vacinados?

In [88]:
df["paciente_idade"].unique()

array([ 69,  81,  51,  65,  56,  39,  79,  22,  62,  67,  83,  76,  44,
        87,  60,  61,  27,  18,  68,  98,  35,  37,  77,  97,  42,  58,
        40,  88,  25,  50,  63,  36,  31,  64,  45,  47,  43,  49,  34,
        74,  38,  73,  72,  57,  71,  48,  29,  95,  70,  66,  85,  30,
        82,  75,  46,  93,  53,  26,  78,  59,  23,  52,  55,  24,  32,
        41,  84,  80,  21,  86,  96,  94,  54,  28,  20,  91,  92,  33,
        99,  90,  19,  89,  17, 101, 102, 121, 107,  16, 104, 103, 100,
       105,   0,  13, 108,   3, 112,   8, 110, 109, 106,   1,  12,  14,
       111], dtype=int64)

In [92]:
menores_18 = df[df['paciente_idade'] < 18]

In [102]:
menores_18['paciente_id'].nunique()

47

In [ ]:
# 5) Quantos estabelecimentos aplicaram vacina no Acre?

In [106]:
df['vacina_fabricante_nome'].nunique()

6

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [128]:
# 1)
df_menores_18 = df[df['paciente_idade'] < 18].copy()
df_menores_18.head()

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem,fl_primeira_dose
1567,fdca313f-b348-422d-94d4-f2c66a87868c-i0b0,f5e6b8c44f7c4d13a87c582def5e8d460435b02f26af8c...,17,2003-07-18,F,4,AMARELA,120025.0,10.0,EPITACIOLANDIA,...,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-05-12,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-05-13T16:16:42.000Z,NaN,1
6250,b7431955-1faa-4c1e-9246-7c1e7b8bb3cb-i0b0,e1a45c07e3c393d5f0eccf4204a7ceab338f4f06696ecb...,16,2004-05-18,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,FUNDACAO BUTANTAN,Organization/61189445000156,2021-01-29,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-06T14:02:07.000Z,NaN,1
9569,fdb8d3b6-14d9-4bcc-9cfe-acd46b4a317a-i0b0,7cf3b238383a70eeb26841c01817737c9706d5b231e8c2...,17,2004-01-23,F,99,SEM INFORMACAO,120020.0,10.0,CRUZEIRO DO SUL,...,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-05-15,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-05-18T03:17:02.000Z,NaN,1
11338,647e2301-3ba4-463a-8d1e-2b6f38a4d99e-i0b0,53eb7fed5faa26ad17ce21ee378f28e25399ab7e90bc05...,17,2003-05-04,F,4,AMARELA,120030.0,10.0,FEIJO,...,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-02-09,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-02-09T22:08:13.000Z,NaN,1
15144,7f469e03-bece-49d0-bebc-33ad98e27f54-i0b0,dbaa6420d8a815158387668d0a59a19cf2bb63958e35d1...,16,2004-08-22,F,5,INDIGENA,120035.0,10.0,MARECHAL THAUMATURGO,...,FUNDACAO BUTANTAN,Organization/61189445000156,2021-01-28,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-09T19:26:03.000Z,NaN,1

In [130]:
# 2)
colunas = df_menores_18.columns.tolist()
colunas

['document_id',
 'paciente_id',
 'paciente_idade',
 'paciente_datanascimento',
 'paciente_enumsexobiologico',
 'paciente_racacor_codigo',
 'paciente_racacor_valor',
 'paciente_endereco_coibgemunicipio',
 'paciente_endereco_copais',
 'paciente_endereco_nmmunicipio',
 'paciente_endereco_nmpais',
 'paciente_endereco_uf',
 'paciente_endereco_cep',
 'paciente_nacionalidade_enumnacionalidade',
 'estabelecimento_valor',
 'estabelecimento_razaosocial',
 'estalecimento_nofantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf',
 'vacina_grupoatendimento_codigo',
 'vacina_grupoatendimento_nome',
 'vacina_categoria_codigo',
 'vacina_categoria_nome',
 'vacina_lote',
 'vacina_fabricante_nome',
 'vacina_fabricante_referencia',
 'vacina_dataaplicacao',
 'vacina_descricao_dose',
 'vacina_codigo',
 'vacina_nome',
 'sistema_origem',
 'data_importacao_rnds',
 'id_sistema_origem',
 'fl_primeira_dose']

In [136]:
# 3)
df_menores_18["vacina_categoria_nome"].nunique()

5

In [138]:
# 4)
colunas_estabelecimento = ['estabelecimento_valor',
 'estabelecimento_razaosocial',
 'estalecimento_nofantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf']
colunas_estabelecimento

['estabelecimento_valor',
 'estabelecimento_razaosocial',
 'estalecimento_nofantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf']

In [142]:
# 5)
df_estabelecimentos = df_menores_18.loc[:, colunas_estabelecimento]
df_estabelecimentos

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1567,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
6250,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
9569,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
11338,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
15144,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
17153,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
18361,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
18608,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
20204,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
20759,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
21119,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
27860,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
29127,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
31200,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
35654,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
38412,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
51872,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
57405,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
61131,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
62742,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
66922,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
68290,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
69882,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,HOSPITAL REGIONAL DO JURUA,120020,CRUZEIRO DO SUL,AC
70881,6697151,MINISTERIO DA SAUDE,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS,120050,SENA MADUREIRA,AC
75368,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
78289,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
79146,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
81424,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
84331,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
88619,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
89601,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
94858,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
95916,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
101402,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE,120080,PORTO ACRE,AC
104776,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
111242,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
116510,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
119906,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
122656,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
123769,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
124696,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
135392,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
136851,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
139074,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
140895,7123043,PREFEITURA MUNICIPAL DE JORDAO,SAUDE DA FAMILIA RIBEIRINHA,120032,JORDAO,AC
142027,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
149043,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
149795,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
152218,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
153347,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
155238,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
161227,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
163168,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
164046,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
164449,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC

In [144]:
df_estabelecimentos_unicos = df_estabelecimentos.drop_duplicates()
df_estabelecimentos_unicos

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1567,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
6250,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
9569,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
11338,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
15144,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
17153,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
18361,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
18608,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
20204,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
21119,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
29127,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
57405,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
61131,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
68290,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
69882,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,HOSPITAL REGIONAL DO JURUA,120020,CRUZEIRO DO SUL,AC
70881,6697151,MINISTERIO DA SAUDE,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS,120050,SENA MADUREIRA,AC
101402,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE,120080,PORTO ACRE,AC
140895,7123043,PREFEITURA MUNICIPAL DE JORDAO,SAUDE DA FAMILIA RIBEIRINHA,120032,JORDAO,AC